# dtype constants
HOUR = "HOUR"
DAY = "DAY"
MONTH = "MONTH"

# status constants
COMPLETED = "COMPLETED"
UNCOMPLETED = "UNCOMPLETED"
NODATA = "NODATA"

# tag category 电流数据的标签类型
TAG = 'TAG'
POINT = 'POINT'
VECTOR = 'VECTOR'

# TAG
TOTAL = 'TOTAL'
PRODUCT = 'PRODUCT'
DEVICE = 'DEVICE'
BUSINESS = 'BUSINESS'
OFFICE = 'OFFICE'
LEASE = 'LEASE'
PUE = 'PUE'
